package com.ecareyun.im.model.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ecareyun.im.model.db.entity.MessageEntity;
import com.ecareyun.im.model.db.entity.SessionEntity;

import com.ecareyun.im.model.db.dao.MessageEntityDao;
import com.ecareyun.im.model.db.dao.SessionEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig messageEntityDaoConfig;
    private final DaoConfig sessionEntityDaoConfig;

    private final MessageEntityDao messageEntityDao;
    private final SessionEntityDao sessionEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        messageEntityDaoConfig = daoConfigMap.get(MessageEntityDao.class).clone();
        messageEntityDaoConfig.initIdentityScope(type);

        sessionEntityDaoConfig = daoConfigMap.get(SessionEntityDao.class).clone();
        sessionEntityDaoConfig.initIdentityScope(type);

        messageEntityDao = new MessageEntityDao(messageEntityDaoConfig, this);
        sessionEntityDao = new SessionEntityDao(sessionEntityDaoConfig, this);

        registerDao(MessageEntity.class, messageEntityDao);
        registerDao(SessionEntity.class, sessionEntityDao);
    }
    
    public void clear() {
        messageEntityDaoConfig.clearIdentityScope();
        sessionEntityDaoConfig.clearIdentityScope();
    }

    public MessageEntityDao getMessageEntityDao() {
        return messageEntityDao;
    }

    public SessionEntityDao getSessionEntityDao() {
        return sessionEntityDao;
    }

}
